name: ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Docker Login and Build
        uses: docker/login-action@v2.0.0
        with:
          username: christopher2p
          password: ${{ secrets.PASSWORD_DOCKERHUB }}
      - name: Build and run Docker container
        run: |
          docker build -t christopher2p/jogo:latest .
          docker run -d -p 3000:3000 christopher2p/jogo:latest
