name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build the application
        run: npm install && npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: christopher2p
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Build Docker image
        run: docker build -t christopher2p/jogo:latest .

      - name: Push Docker image to Docker Hub
        run: docker push christopher2p/jogo:latest

  run-container:
    needs: build-and-push-container
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: christopher2p
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Run Docker container
        run: docker run -d -p 3000:3000 christopher2p/jogo:latest
