name: ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: christopher2p
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Docker container
        run: |
          docker build -t christopher2p/jogo:latest .
          docker run -d -p 3000:3000 christopher2p/jogo:latest
  build:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
