name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: christopher2p
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      with:
  # Username used to log against the Docker registry
          username: christopher2p
  # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.PASSWORD_DOCKERHUB }}
